platform :osx, '10.10'
use_frameworks!

target 'ExampleOSX' do
    #pod 'Alamofire', '~> 3.4.1'
	pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3' # Use Swift 3 branch for now
    #pod 'Decodable', '~> 0.4.3'
    pod 'Decodable', :git => 'https://github.com/Anviking/Decodable.git' # use Swift 3 master branch for now
    pod 'ConnectedDrive', :path => '../../'
end

target 'ExampleOSXTests' do

end
